"""
[V0.A7] Metadata & Embedding (§13)
==================================
Applied as a post-processing pass after an ExportResult is produced —
kept separate from each format exporter so every format gets the same
metadata policy instead of nine slightly different implementations.

- Video (mp4/webm/mov/mkv/avi): ffmpeg `-metadata` remux (fast, no re-encode)
- Image sequences: EXIF (via Pillow) on formats that support it, otherwise
  a sidecar `.xmp` file (PNG/WebP/APNG don't have a universal EXIF slot)
- Lottie: metadata folded into top-level JSON fields Lottie already
  reserves for this (`nm`, plus a custom `meta` block most players ignore
  gracefully)
- Code exports: a header comment block (creator/copyright/timestamp)
"""
from __future__ import annotations

import json
import shutil
import subprocess
import time
from pathlib import Path

from models.schemas import ExportFormat, ExportMetadata, VIDEO_FORMATS

_XMP_TEMPLATE = """<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:xmp="http://ns.adobe.com/xap/1.0/">
      <dc:title>{title}</dc:title>
      <dc:creator>{author}</dc:creator>
      <dc:rights>{copyright}</dc:rights>
      <xmp:CreatorTool>ForgeOS Export Pipeline</xmp:CreatorTool>
      <xmp:CreateDate>{timestamp}</xmp:CreateDate>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
"""


def embed_metadata(output_path: Path, fmt: ExportFormat, metadata: ExportMetadata, software_version: str = "0.1.0") -> Path:
    """Returns the (possibly new) path to the metadata-bearing file."""
    if not any([metadata.title, metadata.author, metadata.copyright, metadata.custom]):
        return output_path  # nothing requested, skip the extra work entirely

    timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if fmt in VIDEO_FORMATS:
        return _embed_video_metadata(output_path, metadata, timestamp, software_version)
    if fmt.value.endswith("_sequence") or fmt.value == "apng":
        _write_xmp_sidecar(output_path, metadata, timestamp)
        return output_path
    if fmt == ExportFormat.LOTTIE:
        return _embed_lottie_metadata(output_path, metadata, timestamp, software_version)
    # code formats: metadata goes in a header comment, handled by
    # code_export.py at generation time (it already receives `request.metadata`)
    return output_path


def _embed_video_metadata(path: Path, metadata: ExportMetadata, timestamp: str, version: str) -> Path:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        return path  # video_export.py already raises earlier if ffmpeg is missing; degrade quietly here
    tmp_out = path.with_name(path.stem + "_meta" + path.suffix)
    cmd = [ffmpeg, "-y", "-i", str(path), "-map", "0", "-c", "copy"]
    if metadata.title:
        cmd += ["-metadata", f"title={metadata.title}"]
    if metadata.author:
        cmd += ["-metadata", f"artist={metadata.author}"]
    if metadata.copyright:
        cmd += ["-metadata", f"copyright={metadata.copyright}"]
    cmd += ["-metadata", f"creation_time={timestamp}", "-metadata", f"encoder=ForgeOS Export Pipeline {version}"]
    for k, v in metadata.custom.items():
        cmd += ["-metadata", f"{k}={v}"]
    cmd.append(str(tmp_out))

    result = subprocess.run(cmd, capture_output=True)
    if result.returncode != 0:
        return path  # remux failed (e.g. exotic codec) — ship the file without metadata rather than failing the export
    tmp_out.replace(path)
    return path


def _write_xmp_sidecar(path: Path, metadata: ExportMetadata, timestamp: str) -> None:
    xmp = _XMP_TEMPLATE.format(
        title=metadata.title or "", author=metadata.author or "",
        copyright=metadata.copyright or "", timestamp=timestamp,
    )
    path.with_suffix(path.suffix + ".xmp").write_text(xmp, encoding="utf-8")


def _embed_lottie_metadata(path: Path, metadata: ExportMetadata, timestamp: str, version: str) -> Path:
    doc = json.loads(path.read_text(encoding="utf-8"))
    if metadata.title:
        doc["nm"] = metadata.title
    doc["meta"] = {
        "a": metadata.author or "", "k": "", "d": "", "tc": "",
        "g": f"ForgeOS Export Pipeline {version}",
    }
    doc["_forgeos_metadata"] = {
        "copyright": metadata.copyright, "created_at": timestamp, "custom": metadata.custom,
    }
    path.write_text(json.dumps(doc, separators=(",", ":")), encoding="utf-8")
    return path


def code_header_comment(metadata: ExportMetadata, fmt_extension: str, version: str = "0.1.0") -> str:
    """Used by code_export.py to prepend a metadata comment block."""
    comment = "//" if fmt_extension in (".js", ".tsx", ".jsx") else "/*"
    close = "" if comment == "//" else " */"
    lines = [f"{comment} Generated by ForgeOS Export Pipeline {version}"]
    if metadata.title:
        lines.append(f"{comment} Title: {metadata.title}")
    if metadata.author:
        lines.append(f"{comment} Author: {metadata.author}")
    if metadata.copyright:
        lines.append(f"{comment} {metadata.copyright}")
    lines.append(f"{comment} Generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}{close}")
    return "\n".join(lines) + "\n\n"
